### ISSUE TITLE
hi, why the model is large to 1 GB?

### ISSUE THREAD

**Issue by lucasjinreal** [HongwenZhang/PyMAF-X#1]
I look inside the code, seems didn't use transformer, why the ckpt so big?

**Comment by HongwenZhang** [comment]
Hi, the model checkpoint contains three subnetworks for body, hand, and face reconstruction. Moreover, each subnetwork also contains a self-attention module (which includes lots of parameters).

**Comment by lucasjinreal** [comment]
@HongwenZhang does the attention module using bert as encoder?

**Comment by HongwenZhang** [comment]
yes
