### ISSUE TITLE
Flame downsampling

### ISSUE THREAD

**Issue by fatbao55** [HongwenZhang/PyMAF-X#16]
Hi, thanks for the good work! I can't seem to find the link to download `flame_downsampling.npz` needed to run the demo. Do you mind sharing the link?

**Comment by HongwenZhang** [comment]
Hi, when downloading [the necessary files](https://github.com/HongwenZhang/PyMAF-X#necessary-files), you should find the `flame_downsampling.npz` in the folder `data`.
![image](https://github.com/HongwenZhang/PyMAF-X/assets/12066626/4b84e73e-cce9-4fbe-94b2-d248c5beada5)

**Comment by fatbao55** [comment]
Thanks for the clarification!

**Comment by AryamanSharma17** [comment]
Hi, I am facing the same issue. I cannot find the link to flame_downsampling.npy as the 'fetch_data.sh' is only meant to fetch 'smpl_downsampling.npz' & 'mano_downsampling.npz'. 

Could you share the download link or path?
Thanks

**Comment by nxrcqupt01** [comment]
Hi, when downloading [the necessary files](https://github.com/HongwenZhang/PyMAF-X#necessary-files), I do not see the  flame_downsampling.npz needed to run the demo. Do you mind sharing the link?

**Comment by fatbao55** [comment]
Hi @nxrcqupt01, you can find them under this [link](https://pan.bnu.edu.cn/l/81f0v6).

**Comment by nxrcqupt01** [comment]
Thank you very much.
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "fatbao55"; 
Date: 2023年7月31日(星期一) 下午4:21
To: "HongwenZhang/PyMAF-X"; 
Cc: "nxrcqupt01"; "Comment"; 
Subject: Re: [HongwenZhang/PyMAF-X] Flame downsampling (Issue #16)

&nbsp;


 
Hi, you can find them under this link.

**Comment by nxrcqupt01** [comment]
您好，请问这3D重建方向的相关学习可以请教下您吗，本人最近刚刚接触3D人体重建这个领域，对您所做的工作比较感兴趣。 方便加您联系方式吗？&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "fatbao55"; 
Date: 2023年7月31日(星期一) 下午4:21
To: "HongwenZhang/PyMAF-X"; 
Cc: "nxrcqupt01"; "Comment"; 
Subject: Re: [HongwenZhang/PyMAF-X] Flame downsampling (Issue #16)

&nbsp;


 
Hi, you can find them under this link.

**Comment by liubc-ai** [comment]
Hi, I found that the corresponding link is not valid, can you provide a new link?

**Comment by HongwenZhang** [comment]
The necessary files have been moved to [this link](https://pan.bnu.edu.cn/l/81f0v6).

**Comment by liubc-ai** [comment]
Thanks for your kind reply
