### ISSUE TITLE
Extremely unstable wrist rotation

### ISSUE THREAD

**Issue by sylyt62** [HongwenZhang/PyMAF-X#2]
Hey,

Great appreciation for your work first! 

I followed the instruction but came up with some strange results on hand poses. Is there anything I was missing?

The command I ran is:
`python -m apps.demo_smplx --vid_file video/hands-test.webm --pretrained_model data/pretrained_model/PyMAF-X_model_checkpoint.pt --misc TRAIN.BHF_MODE full_body MODEL.EVAL_MODE True MODEL.PyMAF.HAND_VIS_TH 0.1`

And a demo results:
https://user-images.githubusercontent.com/80388134/199451658-d03a046b-c22f-42f7-b694-864ca2913a96.mp4

**Comment by HongwenZhang** [comment]
Hi, it seems that the hands were not detected correctly or incompatible mano models were used, could you please upload the video to colab and run the code on colab first?

https://colab.research.google.com/drive/13Iytx1Hb0ZryEwbJdpXBW9ggDxs2Y-tL?usp=sharing

**Comment by sylyt62** [comment]
Oh my bad.. I downloaded openpafpif weights from https://openpifpaf.github.io/intro.html#install instead of directly from the code..

Now the result seems more reasonable. For others reference:
https://user-images.githubusercontent.com/80388134/199457881-efd9f114-fe8f-43a4-ad09-b6cbe8c0c49d.mp4
