### ISSUE TITLE
How to read smplx_params output by smplx.SMPLX?

### ISSUE THREAD

**Issue by Darius-H** [HongwenZhang/PyMAF-X#21]
After running the demo example, i got smplx_params from pickle file, while their tensor shape like this:
<img width="388" alt="image" src="https://github.com/HongwenZhang/PyMAF-X/assets/49788663/c34f1c55-e8bc-4211-8bbf-ac3d7d698eb7">
How can i use SMPLX model to read these params, its parmas' shapes are different from the SMPLX params i used before. The poses params has one more dimension with 3. Can i convert the smplx params to the way that can be accepted by SMPLX model?
The params i used before is:
<img width="323" alt="image" src="https://github.com/HongwenZhang/PyMAF-X/assets/49788663/66bba3f8-4a8d-4450-a60f-0a378c5275c0">

**Comment by Darius-H** [comment]
I found this code useful https://github.com/Skype-line/X-Avatar/blob/main/data_process/preprocess_PymafX_pose.py , but there is a little bug that pymafx's smplx face is not compatible with that one, the smplx version is different.

**Comment by sebastianopazo1** [comment]
Hi @Darius-H! Could you solve the bug opymaf's smplx face?
Thanks for your help

**Comment by R132** [comment]
> I found this code useful https://github.com/Skype-line/X-Avatar/blob/main/data_process/preprocess_PymafX_pose.py , but there is a little bug that pymafx's smplx face is not compatible with that one, the smplx version is different.

That`s useful! Thanks a lot !

**Comment by ZhenyanSun** [comment]
> > I found this code useful https://github.com/Skype-line/X-Avatar/blob/main/data_process/preprocess_PymafX_pose.py , but there is a little bug that pymafx's smplx face is not compatible with that one, the smplx version is different.
> 
> That`s useful! Thanks a lot !

Have you solved the leye_pose and reye_pose converting? Thanks.
