### ISSUE TITLE
Evaluation for provided pretrained model

### ISSUE THREAD

**Issue by pangyyyyy** [HongwenZhang/PyMAF-X#4]
Dear authors, 

Thanks for the great work! I have two questions:

1. For the pretrained checkpoint provided `PyMAF-X_model_checkpoint.pt`, what are the errors (PA-MPJPE, PA-PVE) per body part? Are they the same as the ones reported in your paper?

2. Would you be able to provide the evaluation codes?

Thanks!

**Comment by HongwenZhang** [comment]
Hi, thank you for your questions.
The provided checkpoint should have similar performances with the `PyMAF-X (HR48)` reported in Table 4 of our paper.   The evaluation code is mainly based on ExPose and Hand4Whole. The code would be available when our paper is accepted. Thanks!

**Comment by pangyyyyy** [comment]
Thanks for the clarification!
