### ISSUE TITLE
Regressing Hand Parameters only 

### ISSUE THREAD

**Issue by enesduran** [HongwenZhang/PyMAF-X#7]
First, thank you for the great work and making it open source!

I want to regress solely hand shape, pose from video (translation and root orientation included). What should my running configuration be? I inspected the code but could not found.

Regards.

**Comment by HongwenZhang** [comment]
Hi, thanks for your interest in our work!

The results of PyMAF-X include the hand shape and pose, but it may need to modify several lines of the code.

For hand-only evaluation, the code can run as follows:

`python -m apps.demo_smplx --image_folder examples/coco_images --detection_threshold 0.3 --pretrained_model output/PyMAF-X_model_checkpoint_v1.1.pt --misc TRAIN.BHF_MODE 'hand_only' MODEL.MESH_MODEL mano`

PS: modify `strict=True` to `strict=False` as:
`model.load_state_dict(checkpoint['model'], strict= False)`
at https://github.com/HongwenZhang/PyMAF-X/blob/smplx/apps/demo_smplx.py#L199

Then the network should have the output dictionary as:
https://github.com/HongwenZhang/PyMAF-X/blob/smplx/models/pymaf_net.py#L683

**Comment by enesduran** [comment]
Thank you for your help!
Regards
